### ISSUE TITLE
Drupal 8 stock search api module config files don't work - must be generated by drupal

### ISSUE THREAD

**Issue by dale-c-anderson** [AcroMedia/ansible-role-solr-core-config#1]
Ran in to a site recently where we had to use the config bundle that was retrieved from the Admin UX at /admin/config/search/search-api ... the stock config template from the module was incomplete and resulted in errors.

**Comment by dale-c-anderson** [comment]
D8 does require that the config bundle be generated from drupal.

For D8 , Typically what we've been doing is getting Drupal running, generating the config bundle, committing that to the project repo, (e.g. as a  `/solr_core_confg` dir in that repo), and THEN using this role to put that config in place like so,
```yaml
    - role: geerlingguy.solr 

     ... 
     ... 

     #   This role is added after Drupal is running, and after the /solr_core_config has been retrieved from D8 and committed to the Drupal project's repository.
    - role: acromedia.solr-core-config  
      vars:
        solr_core_name: foo
        solr_core_conf_source: "/home/chs/www/foo/solr_core_config"
```
